### ISSUE TITLE
Possible Bugs

### ISSUE THREAD

**Issue by Akyunnn** [WizarTheGreat/DiamondShop#13]
I finally figured out how to use the plugin and tested a lot of things. 

(I apologize with my English) 

- Some bugs occur sometimes, like sign can be interacted by other player when holding a full stack of diamond, probably on my server only but possible to be a bug

- double chest not protected and can be opened on the side with no shop sign

- can also input item with hopper (not a problem i guess)

- can place more sign in 1 chest by the owner (might be a feature)

- when selling more than 64 item in the sign and  the stock only have less than 64, then that 64 will be given but the buyer diamond will be gone but wont go through the chest

If its fine with you I want to suggest/request to have a configuration on how many shop can be made to limit the player from making too much like limit the shop sign can be made or something.
If its also possible to automatically add a color to the sign to know if the shop is working or not

**Comment by WizarTheGreat** [comment]
I appreciate your documentation and feedback with the plug-in, though I have some questions and comments.
• Is there any way you could show a screenshot or video depicting this other access bug?
• The double chest needs two signs in order to be fully protected, though I don't see an issue with this at the moment.
• Inputting items is supposed to be a way to restock your shop automatically
• Placing more than 1 sign on a chest allows for multiple items to be sold from the same chest (such as with double chests)
• And I will make sure to move the give diamonds function outside of the nonstack check for the next update.

In regards to the configuration, adding a limit to sign placement would allow other players to fill up someone's sign requirement. I could add a function disallowing people access to place shops other than their own, what's your opinion on this?

And you can right click a sign to see if the format is right after making it, so I do not see the purpose of the text change.

**Comment by WizarTheGreat** [comment]
Even stacks now give diamonds, and a max shops config has been added
